version: "3.8"

services:
  hugo-contact:
    build: .
    container_name: hugo-contact
    ports:
      - "8080:8080"
    environment:
      SMTP_HOST: smtp.example.com
      SMTP_PORT: "587"
      SMTP_USERNAME: your@example.com
      SMTP_PASSWORD: yourpassword
      RECIPIENT_EMAIL: your@example.com
      CORS_ALLOW_ORIGIN: "https://yourhugosite.com"
      PORT: "8080"
    restart: unless-stopped
